### PR TITLE
Fix controller odom bug and add namespace to gazebo plugin, it works well in multi robots case now

### PR DESCRIPTION
**Pull request by yizhengzhang1**
Odom didn't work well with multi robots before due to odom name is constant.
Also, add namespace to gazebo plugin to make ekf_localization package work.

It can work well in multi robots case now.

### CODE REVIEW

**Comment by tonybaltovski** [comment]
LGTM, thanks.

**Comment by tonybaltovski** [comment]
@Privilger the `namespace` arg is not used.

**Comment by yizhengzhang1** [comment]
@tonybaltovski the `namespace` arg will be used when you launch the node with `ns` tag.

**Comment by tonybaltovski** [comment]
There was no namespace tag causing it fail.

**Pull request merged**
