### PR TITLE
Add messages for body lighting.

### PR DESCRIPTION
**Pull request by mikepurvis**
The proposed API will be that the MCU will listen on `/mcu/cmd_lights`, and display the commanded pattern, probably with a ~1 second or so timeout, after which it will revert to all-off, or perhaps some generic pattern.

The user can command the lights by publishing to `/cmd_lights`, so there will be a small piece of ridgeback_base which provides the necessary pass-through. In the event of an exceptional situation such as an e-stop, the user's command will be overridden with a system indication.

@tonybaltovski @ablakey Would appreciate a quick sanity check on this.

### CODE REVIEW

**Comment by ablakey** [comment]
What would `ridgeback_msgs/RGB[8] lights` get initialized with by default? nulls permitting a sparse-like array for only setting some of the lights? Admittedly haven't used a set length array in ros msgs; not sure how ros builds the message for both languages.

**Comment by mikepurvis** [comment]
Initialized to zero on startup, so "all lights off".

**Comment by ablakey** [comment]
Cool.  LGTM.

**Comment by tonybaltovski** [comment]
LGTM as well.

**Pull request merged**
